Repository psr7-sessions/storageless, pull requests merged in 2023-07, with the labels that each got.

#574 Fix markdownlint errors
  README.md
Labels: documentation

#568 tests: remove duplicated test code
  test/StoragelessTest/Http/SessionMiddlewareTest.php
Labels: enhancement

#570 Add Config object, drop factory methods
  examples/index.php
  src/Storageless/Http/SessionMiddleware.php
  src/Storageless/Http/SessionMiddlewareConfiguration.php
  test/StoragelessTest/Asset/MutableBadCookie.php
  test/StoragelessTest/Http/SessionMiddlewareConfigurationTest.php
  test/StoragelessTest/Http/SessionMiddlewareTest.php
Labels: enhancement, BC break

#564 Add session hijacking mitigation configuration
  README.md
  composer.json
  composer.lock
  infection.json.dist
  psalm-baseline.xml
  psalm.xml
  src/Storageless/Http/ClientFingerprint/Configuration.php
  src/Storageless/Http/ClientFingerprint/RemoteAddr.php
  src/Storageless/Http/ClientFingerprint/SameOriginRequest.php
  src/Storageless/Http/ClientFingerprint/Source.php
  src/Storageless/Http/ClientFingerprint/SourceMissing.php
  src/Storageless/Http/ClientFingerprint/UserAgent.php
  src/Storageless/Http/SessionMiddleware.php
  src/Storageless/Http/SessionMiddlewareConfiguration.php
  test/StoragelessTest/Http/ClientFingerprint/ConfigurationTest.php
  test/StoragelessTest/Http/ClientFingerprint/RemoteAddrTest.php
  test/StoragelessTest/Http/ClientFingerprint/SameOriginRequestTest.php
  test/StoragelessTest/Http/ClientFingerprint/UserAgentTest.php
  test/StoragelessTest/Http/SessionMiddlewareConfigurationTest.php
  test/StoragelessTest/Http/SessionMiddlewareTest.php
Labels: enhancement

#576 Update documentation to reflect the new Configuration object
  CONTRIBUTING.md
  README.md
  docs/configuration.md
  examples/index.php
  src/Storageless/Http/Configuration.php
  src/Storageless/Http/SessionMiddleware.php
  test/StoragelessTest/Http/ConfigurationTest.php
  test/StoragelessTest/Http/SessionMiddlewareTest.php
Labels: documentation

#577 Fingerprint hash: encode the raw binary to save space
  psalm-baseline.xml
  src/Storageless/Http/ClientFingerprint/SameOriginRequest.php
  test/StoragelessTest/Http/ClientFingerprint/SameOriginRequestTest.php
Labels: enhancement

#578 Client Fingerprint: extract infos from headers where possible
  README.md
  src/Storageless/Http/ClientFingerprint/RemoteAddr.php
  src/Storageless/Http/ClientFingerprint/UserAgent.php
  test/StoragelessTest/Http/ClientFingerprint/RemoteAddrTest.php
  test/StoragelessTest/Http/ClientFingerprint/UserAgentTest.php
Labels: enhancement

#579 Configuration: mutable dependencies shouldn't be cloned
  src/Storageless/Http/Configuration.php
  test/StoragelessTest/Http/ConfigurationTest.php
Labels: bug

#580 Configuration: lets clone third-party config objects
  src/Storageless/Http/Configuration.php
  test/StoragelessTest/Http/ConfigurationTest.php
Labels: bug
